#! /bin/sh

### BEGIN INIT INFO
# Provides:          soft_reset_listener.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting soft_reset_listener.py"
    /usr/local/bin/soft_reset_listener.py &
    ;;
  stop)
    echo "Stopping soft_reset_listener.py"
    pkill -f /usr/local/bin/soft_reset_listener.py
    ;;
  *)
    echo "Usage: /etc/init.d/soft_reset_listener.sh {start|stop}"
    exit 1
    ;;
esac
exit 0
